### PR TITLE
Set userId in langfuse trace if "user" is passed in OpenAI completion API calls

### PR DESCRIPTION
**Pull request by code-haven**
Use the "user" parameter in https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids to be able to group usage by user in https://langfuse.com/docs/user-explorer.

### CODE REVIEW

**Comment by maxdeichmann** [comment]
@code-haven thanks for the contribution. I am happy to push this out asap. Do you mind renaming `user` to `user_id`? Some of our users might insert an object to `user` which would not work. With `user_id` we have higher likelihood of getting strings :)

**Comment by code-haven** [comment]
@maxdeichmann done

**Comment by code-haven** [comment]
oops, looks like the OpenAI library isn't liking the user_id parameter. Have to test if this work again.

**Comment by maxdeichmann** [comment]
> oops, looks like the OpenAI library isn't liking the user_id parameter. Have to test if this work again.

Ok. Is it ok to have it the way it is now? Having the userId on the generation function might be confusing for users.

**Comment by code-haven** [comment]
are you suggesting to create a custom trace with userId and passing trace_id to the chatCompletion call instead of making this change?

**Comment by maxdeichmann** [comment]
> eate a custom trace with userId and passing trace_id to the chatCompletion call instead of making this change (if we leave this as it is now)?

Yes, i think this would be the cleanest solution for now.

**Comment by code-haven** [comment]
ok, sounds good. thanks for the help!

**Pull request closed without merging**
