### PR TITLE
feat(api): mask data from traces logged to langfuse

### PR DESCRIPTION
**Pull request by shawnzhu**
Supports https://github.com/langfuse/langfuse/issues/3518

## Developer Experience

```Python
from langfuse.decorators import observe, langfuse_context

langfuse_context.configure(
  # example lambda to replace "home_address" from input and output
  mask=lambda data: {**data, "home_address": "masked"} if isinstance(data, dict) else data
)

@observe()
def process_pii(home_address: str):
    print("Hello, from the process_pii function!")
 
process_pii("777 this road")

langfuse_context.flush()
```

----

> [!IMPORTANT]
> Add data masking functionality to Langfuse client to protect sensitive information in logs.
> 
>   - **Behavior**:
>     - Add `mask` parameter to `Langfuse` class in `client.py` to mask sensitive data in logs.
>     - Apply `mask` function to `input` and `output` in `trace()`, `span()`, `event()`, and `generation()` methods in `client.py`.
>   - **Configuration**:
>     - Add `mask` parameter to `configure()` in `langfuse_decorator.py` and `get()` in `langfuse_singleton.py`.
>   - **Testing**:
>     - Add `test_mask_input` in `test_core_sdk_unit.py` to verify masking of `input` and `output` data.
>   - **Misc**:
>     - Update docstrings in `client.py` to include `mask` parameter description.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=langfuse%2Flangfuse-python&utm_source=github&utm_medium=referral)<sup> for 7e6bcb6c1573b35b9ad6f3c5f92f68927a438066. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by hassiebp** [comment]
Thanks a lot for your work and for raising this PR @shawnzhu !

In the current state, this PR is not yet handling masking IO from StatefulClients. Rather than applying the mask on the Langfuse Client level, I'd suggest passing the `mask` down to the `task_manager` and apply the mask in the `add_task` method. You can check the event body there whether there are any to-be-masked dict keys and apply the mask there.

**Review by hassiebp — CHANGES_REQUESTED** [review]
Thanks a lot for your work and for raising this PR @shawnzhu !

In the current state, this PR is not yet handling masking IO from StatefulClients. Rather than applying the mask on the Langfuse Client level, I'd suggest passing the mask down to the task_manager and apply the mask in the add_task method. You can check the event body there whether there are any to-be-masked dict keys and apply the mask there.

**Comment by shawnzhu** [comment]
>  I'd suggest passing the mask down to the task_manager and apply the mask in the add_task method

Great idea. Let me try

**Comment by shawnzhu** [comment]
@hassiebp may I ask for a review again?

**Comment by hassiebp** [comment]
Thanks a lot for your contribution, @shawnzhu! Will take it from here in #977 👍🏾

**Pull request merged**
