### PR TITLE
Change in logger & fix for huggingface_hub

### PR DESCRIPTION
**Pull request by Dev-Khant**
Fixes : #16

### CODE REVIEW

**Comment by Dev-Khant** [comment]
@marcklingen @maxdeichmann 1 test was failing even before this changes. So let me know if that needs to fixed now.

**Comment by Dev-Khant** [comment]
@marcklingen Where's the issue I can help there.

**Comment by marcklingen** [comment]
@Dev-Khant No issue, all tests pass locally. Currently figuring out how to safely grant access to GH actions secrets without exposing our OpenAI/HF keys.  I'll merge when I've fixed it

**Review by marcklingen — APPROVED** [review]

**Comment by Dev-Khant** [comment]
Sure, but let me know if you need any help @marcklingen

**Comment by marcklingen** [comment]
I'll merge it into a development branch, we'll need to adapt tests in the future that they can run locally without secrets (against a dockerized version of langfuse/langfuse server), exposing secrets to forks is kind of dangerous and there does not seem to be an easy/safe way to do it.

**Pull request merged**
